### PR TITLE
Do not build glfw shell

### PR DESCRIPTION
**Pull request by jwinarske**
-pass in default of "--no-build-glfw-shell"

Signed-off-by: Joel Winarske <joel.winarske@gmail.com>

### CODE REVIEW

**Comment by ykuzma1** [comment]
Hey @jwinarske,

I'm getting the same error as the CI check for this branch when I build for the raspberry pi (64-bit) even when passing `--no-build-glfw-shell`. Any ideas why it is still trying to build GLFW and look for `X11/Xlib.h`??

**Comment by jwinarske** [comment]
Yeah.  The issue linked in https://github.com/meta-flutter/meta-flutter/issues/4 had just been escalated.  For now you should be able to make progress with beta or stable channel (not gallery).

**Comment by ykuzma1** [comment]
@jwinarske That worked! Changing to stable channel in `flutter-engine.inc` fixed the X11 error. With gallery commented out, the entire build completes successfully.

Next step I still wanted to get gallery working, so I re-added gallery to the image and changed to stable channel in `flutter-sdk_git.inc` as well. I am now getting 

`ERR : Could not find a file named "pubspec.yaml" in "/home/ubuntu/test/raspberrypi3-64/tmp/work/cortexa53-poky-linux/flutter-gallery-release/git-r0/recipe-sysroot-native/usr/share/flutter/sdk/.pub-cache/hosted/pub.dartlang.org/analyzer-2.8.0".`

Probably a stupid question, but do you know why gallery can't be built on stable?

**Comment by jwinarske** [comment]
@ykuzma1 yes. They only guarantee to build on master.  It's the policy of the repo.  It worked on dev about a month ago.  I had filled an issue and they quickly closed it saying it is only guaranteed to build with master.

**Comment by ykuzma1** [comment]
@jwinarske Thank you for patiently explaining!! Other apps are building just fine for me & that is indeed helping me make progress! Let's hope they fix the issue in flutter/flutter soon.

**Comment by jwinarske** [comment]
closing as PR not needed as it has been fixed upstream

**Pull request closed without merging**
