### PR TITLE
gn: Allow networking to use gclient

### PR DESCRIPTION
**Pull request by rzr**
Relate-to: https://booting.oniroproject.org/distro/oniro/-/merge_requests/541
Forwarded: https://github.com/meta-flutter/meta-flutter/pull/82
Signed-off-by: Philippe Coval <philippe.coval@huawei.com>

### CODE REVIEW

**Comment by jwinarske** [comment]
@rzr Looking at your MR it seems you're still using `dunfell`:
https://booting.oniroproject.org/distro/oniro/-/merge_requests/541/diffs#diff-content-e16db4b24d85180b34b7c927f4e5db49d6941d80

What are you using for kirkstone CI job?  It might be easier if I understand your target, and then I can flush out all the issues at once; mitigate the busy work.

**Comment by rzr** [comment]
This MR is outdated, the project has been relocated elsewhere.

My target is currently qemux86-64 but using musl flavour (currently breaking with updated clang)

**Comment by jwinarske** [comment]
Are you building the engine with musl?

**Comment by rzr** [comment]
I'd like too, but i am not sure it's supported well supported according to:
https://github.com/flutter/flutter/issues/46016

Maybe fallback to glibc would be an intermediary step

**Comment by jwinarske** [comment]
@rzr With current flutter-engine recipe now supporting the addition of patches via SRC_URI, everything is in place for a variant like this.  It would most likely require patches for Skia, Dart, and a couple of other places.  It'd be curious to see what one could shrink the size to.

What poky branch is the baseline for kirkstone? `master-next` or `master`?

**Comment by jwinarske** [comment]
@rzr Moved to merging this to kirkstone branch.  I will update CI in kirkstone branch to actually build kirkstone once it's clear what the baseline is.

**Comment by rzr** [comment]
Thx, Currently oniro uses  uninative-3.5-222-gb1bb4e2d73

https://gitlab.eclipse.org/eclipse/oniro-core/oniro/-/blob/kirkstone/manifests/default.xml#L27

**Comment by jwinarske** [comment]
@rzr kirkstone branch CI job has all recipes passing.
https://github.com/meta-flutter/meta-flutter/actions/runs/2061365620
Let me know when you lock to a commit and I will tag it something.

**Pull request merged**
