### PR TITLE
build: Support modern bitbake syntax for appends

### PR DESCRIPTION
**Pull request by rzr**
This will enable support for kirstone branch
and still remain compatible with dunfell.

Signed-off-by: Philippe Coval <philippe.coval@huawei.com>

### CODE REVIEW

**Comment by snke** [comment]
There are recipes missing that change, e.g. `flutter-gallery.inc`.

You might want to run `poky/scripts/contrib/convert-overrides.py` on meta-flutter maybe?

https://docs.yoctoproject.org/migration-guides/migration-3.4.html#override-syntax-changes

**Comment by jwinarske** [comment]
@rzr dunfell is intentionally using old style override specifiers.  Some commercial support does not yet use the new override specifier.  What needs to happen is honister branch needs to move forward to meet dunfell changes.  The primary difference there is the CI jobs.

**Comment by rzr** [comment]
ok so i am closing this PR.

BTW would it make sense to rebase honister branch on dunfell ?

**Comment by jwinarske** [comment]
@rzr rebasing `honister` is on my todo list since I made the AGL release.  The tedious part is smoke testing all the CI jobs.  I figure in the next week it should be done.

**Pull request closed without merging**
