### PR TITLE
Remove FLUTTER_RUNTIME variable

### PR DESCRIPTION
**Pull request by jwinarske**
-Removes BBCLASS extensions that implement FLUTTER_RUNTIME
 Uses flutter-engine PACKAGECONFIG key/value to determine which runtime variants to build
-Packagegroups for flutter apps

Signed-off-by: Joel Winarske <joel.winarske@gmail.com>

### CODE REVIEW

**Comment by jwinarske** [comment]
@ardera heads up.  This may require a refactor for flutter-pi recipe.  Starting build flush out now.

**Comment by jwinarske** [comment]
@WAKazuyoshiAkiyama Upcoming changes.

**Comment by jwinarske** [comment]
Build Matrix is green

Smoke Testing next

**Comment by jwinarske** [comment]
Container image needs busybox added.  Only cd and pwd commands work.  User id uid:gid works.  Using `docker import -c ...` one can set the default user of container.

**Comment by jwinarske** [comment]
RPI Zero2 checks out for flutter-auto and flutter-pi

**Comment by jwinarske** [comment]
dart-sdk on x86_64 requires 
```
mkdir -p /lib64
ln -sf /lib/ld-linux-x86-64.so.2 /lib64/ld-linux-x86-64.so.2
```
need to patch dart-sdk to resolve this.

**Comment by jwinarske** [comment]
Pattern for container use:
```
docker import -c "USER dev" -c "WORKDIR /home/dev" app-container-image-dart-containerx86-64.tar.bz2 app-container-image-dart-containerx86-64:latest
docker run -it <container id> sh
```
If your host logged in user has UID=1000, you can maps R/W shares using:
```
docker run -it -v `pwd`/test:/home/dev/test <container id> sh
```

**Comment by jwinarske** [comment]
Adding `BASELIB = "lib64"` to local.conf avoids symlink required for `dart-sdk`.

**Comment by jwinarske** [comment]
dart-sdk recipe:
1. enables external toolchain build for dart-sdk.  Fix for needing to symlink /lib for 64-bit images.
2. riscv32/riscv64 support

**Comment by jwinarske** [comment]
STM3215MP (32-bit)
* flutter-auto + gallery (release) tested
* dart-sdk not 100%:
```
root@stm32mp15-disco:~# dart --version
Dart SDK version: 2.18.6 (stable) (Tue Dec 13 21:15:14 2022 +0000) on "linux_arm"
root@stm32mp15-disco:~# dart pub global activate protoc_plugin
+ _fe_analyzer_shared 51.0.00.1s)
+ analyzer 5.3.1
+ args 2.3.1
+ async 2.10.0
+ collection 1.17.0
+ convert 3.1.1
+ crypto 3.0.2
+ dart_style 2.2.4
+ file 6.1.4
+ fixnum 1.0.1
+ glob 2.1.1
+ meta 1.8.0
+ package_config 2.1.0
+ path 1.8.3
+ protobuf 2.1.0
+ protoc_plugin 20.0.1
+ pub_semver 2.1.3
+ source_span 1.9.1
+ string_scanner 1.2.0
+ term_glyph 1.2.1
+ typed_data 1.3.1
+ watcher 1.0.2
+ yaml 3.1.1
Building package executables... (31.3s)
Built protoc_plugin:protoc_plugin.
Cannot rename file to '/home/root/.pub-cache/_temp/dirJHJCDY/bin/protoc_plugin.dart-2.18.6.snapshot', path = '/home/root/.pub-cache/_temp/dirJHJCDY/incremental/tmpMTHAFT/protoc_plugin.dart.incremental.dill.incremental.dill' (OS Error: No such file or directory, errno = 2)
Built protoc_plugin:protoc_plugin_bazel.
Cannot rename file to '/home/root/.pub-cache/_temp/dirJHJCDY/bin/protoc_plugin_bazel.dart-2.18.6.snapshot', path = '/home/root/.pub-cache/_temp/dirJHJCDY/incremental/tmpPPLCBF/protoc_plugin_bazel.dart.incremental.dill.incremental.dill' (OS Error: No such file or directory, errno = 2)
root@stm32mp15-disco:~/cli# dart create -t console cli
root@stm32mp15-disco:~/cli# cd cli
root@stm32mp15-disco:~/cli# dart run
Building package executable... (15.6s)
Built cli:cli.
Hello world: 42!
root@stm32mp15-disco:~/cli# dart compile exe bin/cli.dart
Error: AOT compilation failed
Generating AOT kernel dill failed!
```
It builds and runs.  Perf may not be resolvable.  Need to look into FPU settings.

**Comment by jwinarske** [comment]
@ardera 
> Though, with this refactor, is it possible to have multiple instances of the same app, compiled with different flutter runtime modes on the target device?

Correct.  It's based on the yocto package config flags.  It supports all varieties now:
1. Release (default)
2. Profile
3. Debug
3. JIT release

To augment which is built use this pattern from local.conf:
```
PACKAGECONFIG:append:pn-flutter-engine = " profile debug" 
```
This would build release, profile, and debug.

Wonders app Install example:
```
/usr/share/flutter/wonders/<beta SDK Version>/release
/usr/share/flutter/wonders/<beta SDK Version>/profile
/usr/share/flutter/wonders/<beta SDK Version>/debug
```
Symlinks are used for engine artifacts in above cases.

By default the debug app asset bundle install is skipped.  You can override in local.conf if you really want/need it.  The expectation for debug build bundles is that they originate from the host.

Yes it's for Developer scenarios, and Yocto SDK support.  In an SDK scenario you would want all used runtime varieties installed.  Of which you would want to select at build time.

The bbclass scenario came from a dialog I had with AGL release manager.

**Comment by ardera** [comment]
@jwinarske wonderful, thanks!

**Pull request merged**
