### PR TITLE
Enable embedded web server building in flutter

### PR DESCRIPTION
**Pull request by Gmatarrubia**
Since flutter can build web app in native javascript code, it could be used to build a embedded web server/app.
I added a flutter-web.bbclass for building an EWS compilation.
This EWS can be powered with nginx or other web engines.

### CODE REVIEW

**Comment by Gmatarrubia** [comment]
@jwinarske I would appreciate your thoughts on this. I'm currently using this code successfully.

**Comment by jwinarske** [comment]
@Gmatarrubia Hello and thanks for the contribution!
This is great, thanks for taking this on.

Looking at this my first impression is that it would be best to incorporate into the existing flutter-app.inc.  just make it a different platform type.  I have something similar planned for building Linux gtk projects.

Let me make a first pass on this and I will provide some further guidance

**Comment by Gmatarrubia** [comment]
Yes, that was my first though. But I after some tries I turned to this approach for this reasons:

- I don't want to add dependence of flutter-engine. It has a big impact in the building time and it is not needed at all.
- There are a lot of steps in compile task that have to be skipped.
- Perhaps the complexity of flutter-app class increase too much.

Anyhow, If you consider that It would be worth to try, I can try it.

**Comment by jwinarske** [comment]
First pass:  https://github.com/meta-flutter/meta-flutter/pull/373
Validated with gallery web recipe.  Results don't get past loading page on firefox.  Not sure what the required setup there is.  I just loaded it using `file://<web>/index.hml`.  Is there any special setup?

I split the includes apart while maintaining as much common as possible.  This will make it easier when I get around to adding GTK support at some point, as it will be flutter-gtk.bbclass/flutter-gtk.inc.

**Pull request closed without merging**
