### PR TITLE
lib/gn: fix gn fetcher when in debug mode

### PR DESCRIPTION
**Pull request by quaresmajose**
To replicate we can run bitbake in debug mode with:

| bitbake flutter-engine-runtimerelease -D --runonly=fetch

This will rise the following python exception:

| Traceback (most recent call last):
| File "/srv/oe/bitbake/lib/bb/ui/knotty.py", line 685, in main
|    event.msg = taskinfo['title'] + ': ' + event.msg
| TypeError: can only concatenate str (not "int") to str

Signed-off-by: Jose Quaresma <jose.quaresma@foundries.io>

### CODE REVIEW

**Comment by jwinarske** [comment]
Actually this looks fine.  I just grep'd the kirkstone tree, and this looks correct.

**Comment by jwinarske** [comment]
I'll merge after 3.3.2 is complete.

**Comment by quaresmajose** [comment]
> What Distro and version are you using for your build environment?

The issue is disto agnostic and to replicate you need to run bitbake with -D (debug mode) otherwise `logger.debug` is disabled and everything looks good

**Comment by jwinarske** [comment]
That explains it, as I haven't run it in debug mode.  Thanks for the contribution!

**Pull request merged**
