### PR TITLE
build with musl libc

### PR DESCRIPTION
**Pull request by andryblack**
fixes for https://github.com/meta-flutter/meta-flutter/issues/574

### CODE REVIEW

**Comment by andryblack** [comment]
checked with `PACKAGECONFIG:pn-flutter-engine = "release embedder-for-target fontconfig impeller-3d"`

**Comment by jwinarske** [comment]
@andryblack 
* Needs a re-base
* add `resolves https://github.com/meta-flutter/meta-flutter/issues/574` to commit.  It will auto-close the issue when it's merged.
* I need to understand the pedigree of the patches; who wrote them, and where did they come from; licensing concerns.

**Comment by andryblack** [comment]
Patches 2-3 from llvm project:
https://github.com/llvm/llvm-project/commit/8e19a2b43573c0245c8925d38140d76051dfbed0
https://github.com/llvm/llvm-project/commit/939f5a33711370697f9ad1de4267cfc7399dfe86
other written from scratch

**Comment by jwinarske** [comment]
Commit needs to be signed

**Review by jwinarske — APPROVED** [review]

**Comment by jwinarske** [comment]
Thanks for the contribution!

**Pull request merged**
