### PR TITLE
Flutter 3.22.2

### PR DESCRIPTION
**Pull request by SeungkyunKim**
Hello meta-flutter developers,

I updated revision files for lates Flutter v3.22.2
Also I added revision generation script.

The changed files are generated that script file.

- Update Flutter and Dart revision files
- Add tool to generate new revision files

### CODE REVIEW

**Comment by jwinarske** [comment]
This is a partial roll.  meta-flutter-apps gets rolled at the same time.
https://github.com/meta-flutter/workspace-automation/blob/main/roll_meta_flutter.py

**Comment by jwinarske** [comment]
Closing in favor of https://github.com/meta-flutter/meta-flutter/pull/513

**Comment by jwinarske** [comment]
@SeungkyunKim also it's clear you had not tested your PR, as these changes are required on top of 3.22.2:
https://github.com/meta-flutter/meta-flutter/pull/517/commits

**Comment by SeungkyunKim** [comment]
First of all, this change is not breaking build before upgradeing FLUTTER_SDK_TAG variable.
I knew additional patch works is needed for v3.22.2. This change was just for updating version information before new patching.

**Pull request closed without merging**
