### PR TITLE
Fix incorrect LICENSE from BSD3-Clause to BSD-3-Clause

### PR DESCRIPTION
**Pull request by marex**
The correct LICENSE is BSD-3-Clause with a dash, update the LICENSE assignment in all recipes where this is not correct. This fixes OE build errors like these:

```
ERROR: flutter-... do_populate_lic: QA Issue: flutter-...: No generic license file exists for: BSD3-Clause in any provider [license-exists]
ERROR: flutter-... do_populate_lic: Fatal QA errors were found, failing task.
```

### CODE REVIEW

**Comment by jwinarske** [comment]
@marex hey thanks for the great catch.  Did you use the roll_meta_flutter.py to update the app recipes?

Also note I am putting together an upcoming AGL release so there will be some churn in the next week.

**Comment by jwinarske** [comment]
https://github.com/meta-flutter/meta-flutter/pull/416

**Comment by marex** [comment]
> @marex hey thanks for the great catch. Did you use the roll_meta_flutter.py to update the app recipes?

No, plain `git grep -l` and `sed -i` .

> Also note I am putting together an upcoming AGL release so there will be some churn in the next week.

Hmmm, looking at the replacement MR, that is awful. Instead of having one well separated fix for one issue (licensing) and with description of the issue in a commit message, there is now a mega-commit doing multiple disparate things all mashed together, and the authorship of this fix also went out of the window.

**Comment by jwinarske** [comment]
You have some good points.  My intent was/is not to take away the contribution you made.

The process to change any of the app recipes is now:

1. edit `conf/include/flutter-apps.json`

2. run roller script:
```
./roll_meta_flutter.py --path /mnt/raid10/meta-flutter --json /mnt/raid10/meta-flutter/conf/include/flutter-apps.json
```
https://github.com/meta-flutter/workspace-automation/blob/main/roll_meta_flutter.py

3. check into a feature branch and test.  Run image build with all the package group recipes, and if meta-gnome is enabled include the file selector example.

4. Create PR of tested changes.

Given the auto-roller touches all but two of the app recipes (I can now get some of my life back), it is a massive PR.  One change in approach to help keep commits easy to follow would be to only check in the flutter-apps.json change.  Independent of the roll. 

The other issue around grouping commits is that there is a massive time span in running tests and validating changes.  Keeping separate commits sometimes is impractical due to the span of time required to test things end to end.  For example the PR I merged for this spanned a number of days given my current workload, and it also required some changes in workspace-automation work, etc.  The update to 3.19.1 was a result of the auto-roll.

**Comment by marex** [comment]
> You have some good points. My intent was/is not to take away the contribution you made.
> 
> The process to change any of the app recipes is now:
> 
>     1. edit `conf/include/flutter-apps.json`
> 
>     2. run roller script:
> 
> 
> ```
> ./roll_meta_flutter.py --path /mnt/raid10/meta-flutter --json /mnt/raid10/meta-flutter/conf/include/flutter-apps.json
> ```
> 
> https://github.com/meta-flutter/workspace-automation/blob/main/roll_meta_flutter.py
> 
>     3. check into a feature branch and test.  Run image build with all the package group recipes, and if meta-gnome is enabled include the file selector example.
> 
>     4. Create PR of tested changes.
> 
> 
> Given the auto-roller touches all but two of the app recipes (I can now get some of my life back), it is a massive PR. One change in approach to help keep commits easy to follow would be to only check in the flutter-apps.json change. Independent of the roll.
> 
> The other issue around grouping commits is that there is a massive time span in running tests and validating changes. Keeping separate commits sometimes is impractical due to the span of time required to test things end to end. For example the PR I merged for this spanned a number of days given my current workload, and it also required some changes in workspace-automation work, etc. The update to 3.19.1 was a result of the auto-roll.

There is literally zero need for such involved manual multi-day testing. The change adjusts the recipe LICENSE, nothing else.

All that was needed to detect this issue was this in local.conf:

```
WARN_QA:remove = "incompatible-license license-exists license-no-generic license-syntax license-format license-incompatible license-file-missing obsolete-license"
ERROR_QA:append = " incompatible-license license-exists license-no-generic license-syntax license-format license-incompatible license-file-missing obsolete-license"
```

If there is a defective LICENSE string, the build will fail, all automatically.

**Comment by jwinarske** [comment]
That might be a good addition to the readme.

Anything requires testing before merging.  It's part of the process in making reliable software.

**Pull request closed without merging**
